// <auto-generated />
using System;
using Cinema.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Cinema.Domain.Entities.Auditorium", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auditoriums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Name = "Hall 1"
                        });
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d1e2f3a-4b5c-4d6e-8f90-000000000001"),
                            Category = "Sci-Fi",
                            DurationMinutes = 148,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("6d1e2f3a-4b5c-4d6e-8f90-000000000002"),
                            Category = "Crime",
                            DurationMinutes = 175,
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            Id = new Guid("6d1e2f3a-4b5c-4d6e-8f90-000000000003"),
                            Category = "Animation",
                            DurationMinutes = 125,
                            Title = "Spirited Away",
                            Year = 2001
                        },
                        new
                        {
                            Id = new Guid("6d1e2f3a-4b5c-4d6e-8f90-000000000004"),
                            Category = "Comedy",
                            DurationMinutes = 99,
                            Title = "The Grand Budapest Hotel",
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("6d1e2f3a-4b5c-4d6e-8f90-000000000005"),
                            Category = "Action",
                            DurationMinutes = 120,
                            Title = "Mad Max: Fury Road",
                            Year = 2015
                        });
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShowtimeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShowtimeId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditoriumId", "Row", "Number")
                        .IsUnique();

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000001000001"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000001000002"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 2,
                            Row = 1
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000001000003"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 3,
                            Row = 1
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000001000004"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 4,
                            Row = 1
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000001000005"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 5,
                            Row = 1
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000001000006"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 6,
                            Row = 1
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000001000007"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 7,
                            Row = 1
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000001000008"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 8,
                            Row = 1
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000002000001"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000002000002"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 2,
                            Row = 2
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000002000003"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 3,
                            Row = 2
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000002000004"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 4,
                            Row = 2
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000002000005"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 5,
                            Row = 2
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000002000006"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 6,
                            Row = 2
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000002000007"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 7,
                            Row = 2
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000002000008"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 8,
                            Row = 2
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000003000001"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000003000002"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 2,
                            Row = 3
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000003000003"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 3,
                            Row = 3
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000003000004"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 4,
                            Row = 3
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000003000005"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 5,
                            Row = 3
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000003000006"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 6,
                            Row = 3
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000003000007"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 7,
                            Row = 3
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000003000008"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 8,
                            Row = 3
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000004000001"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000004000002"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 2,
                            Row = 4
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000004000003"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 3,
                            Row = 4
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000004000004"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 4,
                            Row = 4
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000004000005"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 5,
                            Row = 4
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000004000006"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 6,
                            Row = 4
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000004000007"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 7,
                            Row = 4
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000004000008"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 8,
                            Row = 4
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000005000001"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000005000002"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 2,
                            Row = 5
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000005000003"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 3,
                            Row = 5
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000005000004"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 4,
                            Row = 5
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000005000005"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 5,
                            Row = 5
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000005000006"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 6,
                            Row = 5
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000005000007"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 7,
                            Row = 5
                        },
                        new
                        {
                            Id = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000005000008"),
                            AuditoriumId = new Guid("0d3a1b6e-1c4f-4a2d-9b7e-000000000001"),
                            Number = 8,
                            Row = 5
                        });
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Showtime", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("AuditoriumId", "StartTime");

                    b.ToTable("Showtimes", (string)null);
                });

            modelBuilder.Entity("Cinema.Domain.Entities.ShowtimeSeat", b =>
                {
                    b.Property<Guid>("ShowtimeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ShowtimeId", "SeatId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatId");

                    b.ToTable("ShowtimeSeats", (string)null);
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Cinema.Domain.Entities.Showtime", null)
                        .WithMany()
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Seat", b =>
                {
                    b.HasOne("Cinema.Domain.Entities.Auditorium", null)
                        .WithMany("Seats")
                        .HasForeignKey("AuditoriumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Showtime", b =>
                {
                    b.HasOne("Cinema.Domain.Entities.Auditorium", null)
                        .WithMany()
                        .HasForeignKey("AuditoriumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.Entities.ShowtimeSeat", b =>
                {
                    b.HasOne("Cinema.Domain.Entities.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cinema.Domain.Entities.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cinema.Domain.Entities.Showtime", null)
                        .WithMany()
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cinema.Domain.Entities.Auditorium", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
